/* ==================== PRODUCT DATA ==================== */
const products = [
  {
    id: 1,
    name: "Heart Chain",
    price: 129,
    category: "Chains",
    image: "images/heart-chain.jpeg",
    description: "Delicate heart-shaped chain, perfect for everyday wear.",
  },
  {
    id: 2,
    name: "Classic Jhumkas",
    price: 49,
    category: "Earrings",
    image: "images/jhumkas.jpeg",
    description: "Timeless jhumkas with intricate detailing.",
  },
  {
    id: 3,
    name: "Pink Bracelet",
    price: 70,
    category: "Earrings",
    image: "images/pink_bracelet.jpeg",
    description: "A set of 4 designer jhumkas for every occasion.",
  },
  {
    id: 4,
    name: "Butterfly Earrings",
    price: 50,
    category: "Earrings",
    image: "images/butterfly-earings.jpeg",
    description: "Lightweight butterfly earrings with a playful charm.",
  },
  {
    id: 5,
    name: "Butterfly Handcuff",
    price: 70,
    category: "Bracelets",
    image: "images/butterfly-handcuff.jpeg",
    description: "Statement butterfly cuff bracelet, bold and elegant.",
  },
  {
    id: 6,
    name: "Pearl Bracelet",
    price: 120,
    category: "Bracelets",
    image: "images/pearl-bracelet.jpeg",
    description: "Classic pearl bracelet, refined and timeless.",
  },
  {
    id: 7,
    name: "Floral",
    price: 170,
    category: "Clips",
    image: "images/floral.jpeg",
    description: "Floral-inspired clip with a feminine touch.",
  },
  {
    id: 8,
    name: "Panda Chain",
    price: 150,
    category: "Chains",
    image: "images/panda-chain.jpeg",
    description: "Cute panda charm chain, fun and trendy.",
  },
];
